# Generated by Django 4.2.17 on 2024-12-23 19:08

import django.core.validators
from django.db import migrations, models
import khakBardari.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranande_id', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True, validators=[khakBardari.models.validate_phone])),
                ('logo', models.ImageField(blank=True, default='Driver_logo/driver_default_logo.png', null=True, upload_to='Driver_logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])),
                ('car_type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('car_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
