# Generated by Django 4.2.17 on 2024-12-24 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khakBardari', '0002_servicekhak'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicekhak',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 24, 14, 12, 48, 446358, tzinfo=datetime.timezone.utc)),
        ),
    ]
